initial commit of docs, including structure and autodoc of specific m…
gretelai/trainer pull request #23
Opened 2022-10-11 20:46 UTC by MasonEgger

…odules

2022-10-11 20:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gretelai/trainer?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gretelai/trainer?pullRequest=23) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gretelai/trainer?pullRequest=23) it.</sub>

2022-10-11 20:53 UTC, csbailey5t commented on README.md
> +## Join they Synthetic Data Community Discord
```suggestion
## Join the Synthetic Data Community Discord
```

2022-10-11 21:07 UTC, zredlined approved these changes

2022-10-12 13:12 UTC, csbailey5t requested changes
Minor punctuation changes for consistency, then good to go

2022-10-12 13:12 UTC, csbailey5t commented on docs/index.rst
> +#. Install the Gretel CLI and Gretel Trainer either on your system or in your Notebook
```suggestion
#. Install the Gretel CLI and Gretel Trainer either on your system or in your Notebook.
```

2022-10-12 13:12 UTC, csbailey5t commented on docs/index.rst
> +#. Train or fine-tune a model using the Gretel API
```suggestion
#. Train or fine-tune a model using the Gretel API.
```

2022-10-12 13:12 UTC, csbailey5t commented on docs/index.rst
> +ask questions, suggest new features or participate in the development meetings, please join
```suggestion
ask questions, suggest new features, or participate in the development meetings, please join
```

2022-10-12 13:12 UTC, csbailey5t commented on docs/quickstart.rst
> +#. Install the Gretel CLI and Gretel Trainer either on your system or in your Notebook
```suggestion
#. Install the Gretel CLI and Gretel Trainer either on your system or in your Notebook.
```

2022-10-12 13:12 UTC, csbailey5t commented on docs/quickstart.rst
> +#. Train or fine-tune a model using the Gretel API
```suggestion
#. Train or fine-tune a model using the Gretel API.
```

2022-10-12 13:12 UTC, csbailey5t commented on docs/quickstart.rst
> +#. Load and preview the dataset, set seed fields
```suggestion
#. Load and preview the dataset, and set seed fields.
```

2022-10-12 13:12 UTC, csbailey5t commented on docs/quickstart.rst
> +#. Train the model
```suggestion
#. Train the model.
```

2022-10-12 13:12 UTC, csbailey5t commented on docs/quickstart.rst
> +#. Conditionally generate data
```suggestion
#. Conditionally generate data.
```

2022-10-12 18:34 UTC, csbailey5t approved these changes

2022-10-12 18:35 UTC, merged